services:
  - type: web
    name: aeropuertohaider-api
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    plan: free
